
multi-tenancy:
  tenants:
    - id: customer-1
      mongo:
        authentication-database: admin
        database: customer1data
        username: root
        password: example
    - id: customer-2
      mongo:
        authentication-database: admin
        database: customer2data
        username: root
        password: example

